### PR TITLE
Fixed code to find keystore location in grails 2.x

### PR DESCRIPTION
**Pull request by euvitudo**
Fixed code to find keystore location in grails 2.x.

Bumped to 2.1.1.

Updated as v1.2, which may not be warranted.

Also, test-app was complaining about hsqldb, so I updated DataSource to use h2.

### CODE REVIEW

**Comment by hartsock** [comment]
Thanks for the contribution!

**Comment by hartsock** [comment]
Always nice to get a well written and well targeted merge like this!

**Comment by euvitudo** [comment]
Thanks for the feedback!

**Comment by tasneem93** [comment]
Hi Shawn,

I am trying to use this plugin "weak-ssl:1.0" in my grails app (v2.3.4) and it is not working. Says "could not read the file ....grails\2.3.4\ssl\keystore". So I find the thread where "euvitudo" fixed this issue and you merged his code to the Master branch.

So is the grails plugin version still 1.0 or is there a new one you published. Please let me know. Thanks in advance.

**Comment by hartsock** [comment]
Actually, I need to find someone to take over maintaining this plugin. I have not done anything with Grails in years at this point so I'm very rusty on what needs to happen.

**Pull request merged**
